# Generated by Django 5.0.1 on 2024-01-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Disease', models.CharField(max_length=100)),
                ('Fever', models.CharField(choices=[(1, 'No'), (0, 'Yes')], max_length=10)),
                ('Cough', models.CharField(choices=[(1, 'No'), (0, 'Yes')], max_length=10)),
                ('Fatigue', models.CharField(choices=[(1, 'No'), (0, 'Yes')], max_length=10)),
                ('Difficult_Breathing', models.CharField(choices=[(1, 'No'), (0, 'Yes')], max_length=10)),
                ('Age', models.PositiveBigIntegerField()),
                ('Gender', models.CharField(choices=[(0, 'Female'), (1, 'Male')], max_length=10)),
                ('Blood_Pressure', models.CharField(max_length=30)),
                ('Cholesterol_Level', models.CharField(max_length=30)),
                ('Result', models.CharField(max_length=10)),
                ('classification', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
