# Generated by Django 5.0.1 on 2024-01-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0003_alter_data_age_alter_data_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.PositiveIntegerField(choices=[(1, 'youngester'), (0, 'teen'), (2, 'adult'), (3, 'senior citizen')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Disease',
            field=models.PositiveIntegerField(choices=[(2, 'Lyme Disease'), (2, 'Cholera'), (3, 'Urinary Tract Infection (UTI)'), (6, 'Gastroenteritis'), (5, 's Disease"'), (2, 'Typhoid Fever'), (6, 'Common Cold'), (14, 'Osteoporosis'), (2, 'Ebola Virus'), (7, 'Hyperthyroidism'), (6, 'Allergic Rhinitis'), (23, 'Asthma'), (5, 'Liver Disease'), (10, 'Migraine'), (5, 'Urinary Tract Infection'), (2, 'Chickenpox'), (6, 'Anxiety Disorders'), (2, 'Malaria'), (2, 'Rabies'), (2, 'Turner Syndrome'), (5, 'Coronary Artery Disease'), (5, 'Kidney Disease'), (1, 'Others'), (2, 'Zika Virus'), (2, 'Measles'), (6, 'Rheumatoid Arthritis'), (2, 'Rubella'), (10, 'Diabetes'), (8, 'Influenza'), (8, 'Bronchitis'), (5, 'Pancreatitis'), (10, 'Hypertension'), (5, 'Multiple Sclerosis'), (6, 'Depression'), (5, 'Psoriasis'), (4, 'Chronic Obstructive Pulmonary Disease (COPD)'), (8, 'Pneumonia'), (3, 'Lung Cancer'), (7, 'Hypothyroidism'), (2, 'Dengue Fever'), (2, 'Hepatitis B'), (6, 'Kidney Cancer'), (6, 'Osteoarthritis'), (2, 'Mumps'), (2, 'Hemophilia'), (16, 'Stroke'), (5, 'Ulcerative Colitis'), (3, 'Hepatitis'), (3, 'Tuberculosis'), (6, 'Eczema'), (2, 'Tetanus'), (6, 'Liver Cancer'), (2, 'Klinefelter Syndrome'), (2, 'HIV/AIDS')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Gender',
            field=models.PositiveIntegerField(choices=[(0, 'Female'), (1, 'Male')]),
        ),
    ]
