# Generated by Django 5.0.1 on 2024-01-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0004_alter_data_age_alter_data_disease_alter_data_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.PositiveIntegerField(choices=[(2, 'adult'), (1, 'youngester'), (3, 'senior citizen'), (0, 'teen')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Blood_Pressure',
            field=models.PositiveIntegerField(choices=[(2, 'High'), (0, 'Low'), (1, 'Normal')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Cholesterol_Level',
            field=models.PositiveIntegerField(choices=[(2, 'High'), (0, 'Low'), (1, 'Normal')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Cough',
            field=models.PositiveIntegerField(choices=[(1, 'No'), (0, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Difficult_Breathing',
            field=models.PositiveIntegerField(choices=[(1, 'No'), (0, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Disease',
            field=models.PositiveIntegerField(choices=[(2, 'Hemophilia'), (6, 'Osteoarthritis'), (2, 'Rabies'), (5, 'Multiple Sclerosis'), (5, 'Urinary Tract Infection'), (10, 'Migraine'), (10, 'Diabetes'), (2, 'Klinefelter Syndrome'), (6, 'Depression'), (2, 'Measles'), (6, 'Gastroenteritis'), (1, 'Others'), (3, 'Hepatitis'), (2, 'Cholera'), (2, 'Turner Syndrome'), (6, 'Anxiety Disorders'), (2, 'Dengue Fever'), (23, 'Asthma'), (5, 'Kidney Disease'), (7, 'Hyperthyroidism'), (3, 'Lung Cancer'), (2, 'Lyme Disease'), (2, 'Zika Virus'), (8, 'Influenza'), (6, 'Common Cold'), (5, 'Coronary Artery Disease'), (4, 'Chronic Obstructive Pulmonary Disease (COPD)'), (6, 'Liver Cancer'), (16, 'Stroke'), (7, 'Hypothyroidism'), (8, 'Bronchitis'), (2, 'Tetanus'), (10, 'Hypertension'), (2, 'HIV/AIDS'), (5, 'Ulcerative Colitis'), (2, 'Typhoid Fever'), (5, 'Liver Disease'), (2, 'Mumps'), (2, 'Malaria'), (2, 'Ebola Virus'), (3, 'Urinary Tract Infection (UTI)'), (3, 'Tuberculosis'), (6, 'Kidney Cancer'), (8, 'Pneumonia'), (6, 'Eczema'), (14, 'Osteoporosis'), (6, 'Rheumatoid Arthritis'), (2, 'Chickenpox'), (6, 'Allergic Rhinitis'), (5, 's Disease"'), (2, 'Hepatitis B'), (5, 'Pancreatitis'), (5, 'Psoriasis'), (2, 'Rubella')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Fatigue',
            field=models.PositiveIntegerField(choices=[(1, 'No'), (0, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Fever',
            field=models.PositiveIntegerField(choices=[(1, 'No'), (0, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='classification',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
