# Generated by Django 5.0.1 on 2024-01-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0005_alter_data_age_alter_data_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.PositiveIntegerField(choices=[(2, 'adult'), (1, 'youngester'), (0, 'teen'), (3, 'senior citizen')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Blood_Pressure',
            field=models.PositiveIntegerField(choices=[(0, 'Low'), (2, 'High'), (1, 'Normal')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Cholesterol_Level',
            field=models.PositiveIntegerField(choices=[(0, 'Low'), (2, 'High'), (1, 'Normal')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Disease',
            field=models.PositiveIntegerField(choices=[(2, 'Measles'), (7, 'Hypothyroidism'), (6, 'Anxiety Disorders'), (8, 'Pneumonia'), (6, 'Gastroenteritis'), (6, 'Eczema'), (5, 'Ulcerative Colitis'), (5, 'Psoriasis'), (3, 'Lung Cancer'), (6, 'Depression'), (14, 'Osteoporosis'), (2, 'Zika Virus'), (5, 'Kidney Disease'), (23, 'Asthma'), (6, 'Liver Cancer'), (2, 'Mumps'), (5, 'Pancreatitis'), (6, 'Kidney Cancer'), (2, 'Chickenpox'), (5, 's Disease"'), (2, 'Malaria'), (2, 'HIV/AIDS'), (6, 'Rheumatoid Arthritis'), (10, 'Migraine'), (10, 'Hypertension'), (6, 'Allergic Rhinitis'), (2, 'Dengue Fever'), (5, 'Multiple Sclerosis'), (2, 'Klinefelter Syndrome'), (5, 'Urinary Tract Infection'), (3, 'Tuberculosis'), (2, 'Tetanus'), (5, 'Liver Disease'), (6, 'Osteoarthritis'), (8, 'Bronchitis'), (2, 'Typhoid Fever'), (2, 'Cholera'), (1, 'Others'), (7, 'Hyperthyroidism'), (2, 'Turner Syndrome'), (5, 'Coronary Artery Disease'), (2, 'Rabies'), (16, 'Stroke'), (3, 'Hepatitis'), (2, 'Rubella'), (6, 'Common Cold'), (2, 'Hepatitis B'), (2, 'Hemophilia'), (2, 'Ebola Virus'), (3, 'Urinary Tract Infection (UTI)'), (2, 'Lyme Disease'), (8, 'Influenza'), (4, 'Chronic Obstructive Pulmonary Disease (COPD)'), (10, 'Diabetes')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Gender',
            field=models.PositiveIntegerField(choices=[(1, 'Male'), (0, 'Female')]),
        ),
    ]
