# Generated by Django 5.0.1 on 2024-01-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0006_alter_data_age_alter_data_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.PositiveIntegerField(choices=[(3, 'senior citizen'), (0, 'teen'), (2, 'adult'), (1, 'youngester')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Disease',
            field=models.PositiveIntegerField(choices=[(16, 'Stroke'), (3, 'Urinary Tract Infection (UTI)'), (2, 'Hemophilia'), (4, 'Chronic Obstructive Pulmonary Disease (COPD)'), (5, 'Ulcerative Colitis'), (6, 'Liver Cancer'), (5, 'Pancreatitis'), (5, 'Kidney Disease'), (2, 'Ebola Virus'), (6, 'Osteoarthritis'), (2, 'Measles'), (5, 'Urinary Tract Infection'), (2, 'Lyme Disease'), (2, 'Turner Syndrome'), (5, 'Liver Disease'), (2, 'Malaria'), (6, 'Gastroenteritis'), (6, 'Eczema'), (2, 'HIV/AIDS'), (2, 'Zika Virus'), (2, 'Chickenpox'), (2, 'Klinefelter Syndrome'), (2, 'Mumps'), (14, 'Osteoporosis'), (3, 'Tuberculosis'), (8, 'Bronchitis'), (2, 'Rabies'), (5, 'Coronary Artery Disease'), (2, 'Dengue Fever'), (5, 'Multiple Sclerosis'), (6, 'Depression'), (8, 'Pneumonia'), (2, 'Rubella'), (5, 'Psoriasis'), (3, 'Hepatitis'), (6, 'Allergic Rhinitis'), (6, 'Anxiety Disorders'), (10, 'Diabetes'), (3, 'Lung Cancer'), (6, 'Kidney Cancer'), (10, 'Migraine'), (2, 'Typhoid Fever'), (5, 's Disease"'), (10, 'Hypertension'), (7, 'Hyperthyroidism'), (7, 'Hypothyroidism'), (2, 'Cholera'), (2, 'Hepatitis B'), (6, 'Common Cold'), (23, 'Asthma'), (8, 'Influenza'), (1, 'Others'), (6, 'Rheumatoid Arthritis'), (2, 'Tetanus')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Gender',
            field=models.PositiveIntegerField(choices=[(0, 'Female'), (1, 'Male')]),
        ),
    ]
