# Generated by Django 5.0.1 on 2024-01-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0007_alter_data_age_alter_data_disease_alter_data_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.PositiveIntegerField(choices=[(2, 'adult'), (0, 'teen'), (1, 'youngester'), (3, 'senior citizen')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Blood_Pressure',
            field=models.PositiveIntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Cholesterol_Level',
            field=models.PositiveIntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Disease',
            field=models.PositiveIntegerField(choices=[(2, 'HIV/AIDS'), (6, 'Liver Cancer'), (3, 'Hepatitis'), (5, 'Kidney Disease'), (3, 'Tuberculosis'), (3, 'Urinary Tract Infection (UTI)'), (5, 's Disease"'), (2, 'Cholera'), (2, 'Mumps'), (6, 'Kidney Cancer'), (6, 'Gastroenteritis'), (5, 'Coronary Artery Disease'), (2, 'Measles'), (2, 'Malaria'), (5, 'Ulcerative Colitis'), (8, 'Bronchitis'), (10, 'Hypertension'), (7, 'Hypothyroidism'), (2, 'Tetanus'), (6, 'Anxiety Disorders'), (2, 'Rabies'), (2, 'Turner Syndrome'), (2, 'Dengue Fever'), (8, 'Influenza'), (2, 'Rubella'), (6, 'Depression'), (5, 'Liver Disease'), (2, 'Klinefelter Syndrome'), (1, 'Others'), (5, 'Multiple Sclerosis'), (6, 'Common Cold'), (6, 'Eczema'), (14, 'Osteoporosis'), (10, 'Diabetes'), (5, 'Psoriasis'), (2, 'Chickenpox'), (6, 'Rheumatoid Arthritis'), (10, 'Migraine'), (5, 'Urinary Tract Infection'), (2, 'Hemophilia'), (2, 'Hepatitis B'), (6, 'Allergic Rhinitis'), (23, 'Asthma'), (2, 'Lyme Disease'), (8, 'Pneumonia'), (5, 'Pancreatitis'), (2, 'Typhoid Fever'), (16, 'Stroke'), (2, 'Zika Virus'), (2, 'Ebola Virus'), (4, 'Chronic Obstructive Pulmonary Disease (COPD)'), (7, 'Hyperthyroidism'), (6, 'Osteoarthritis'), (3, 'Lung Cancer')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Gender',
            field=models.PositiveIntegerField(choices=[(1, 'Male'), (0, 'Female')]),
        ),
    ]
