# Generated by Django 5.0.1 on 2024-01-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0008_alter_data_age_alter_data_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.PositiveIntegerField(choices=[(1, 'youngester'), (2, 'adult'), (3, 'senior citizen'), (0, 'teen')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Blood_Pressure',
            field=models.PositiveIntegerField(choices=[(2, 'High'), (1, 'Normal'), (0, 'Low')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Cholesterol_Level',
            field=models.PositiveIntegerField(choices=[(2, 'High'), (1, 'Normal'), (0, 'Low')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Disease',
            field=models.PositiveIntegerField(choices=[(6, 'Rheumatoid Arthritis'), (8, 'Pneumonia'), (5, 'Liver Disease'), (6, 'Gastroenteritis'), (3, 'Tuberculosis'), (2, 'Klinefelter Syndrome'), (6, 'Osteoarthritis'), (10, 'Migraine'), (2, 'HIV/AIDS'), (2, 'Rabies'), (3, 'Lung Cancer'), (5, 'Pancreatitis'), (5, 'Psoriasis'), (6, 'Kidney Cancer'), (6, 'Depression'), (2, 'Turner Syndrome'), (8, 'Influenza'), (10, 'Diabetes'), (23, 'Asthma'), (5, 'Kidney Disease'), (6, 'Allergic Rhinitis'), (2, 'Rubella'), (5, 's Disease"'), (2, 'Malaria'), (6, 'Anxiety Disorders'), (7, 'Hyperthyroidism'), (5, 'Coronary Artery Disease'), (2, 'Measles'), (2, 'Tetanus'), (3, 'Urinary Tract Infection (UTI)'), (7, 'Hypothyroidism'), (8, 'Bronchitis'), (2, 'Dengue Fever'), (2, 'Typhoid Fever'), (2, 'Lyme Disease'), (5, 'Multiple Sclerosis'), (2, 'Mumps'), (2, 'Ebola Virus'), (6, 'Eczema'), (16, 'Stroke'), (2, 'Chickenpox'), (3, 'Hepatitis'), (5, 'Ulcerative Colitis'), (4, 'Chronic Obstructive Pulmonary Disease (COPD)'), (6, 'Common Cold'), (2, 'Zika Virus'), (2, 'Hepatitis B'), (10, 'Hypertension'), (2, 'Hemophilia'), (6, 'Liver Cancer'), (14, 'Osteoporosis'), (2, 'Cholera'), (1, 'Others'), (5, 'Urinary Tract Infection')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Gender',
            field=models.PositiveIntegerField(choices=[(0, 'Female'), (1, 'Male')]),
        ),
    ]
