# Generated by Django 5.0.1 on 2024-01-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0009_alter_data_age_alter_data_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.PositiveIntegerField(choices=[(3, 'senior citizen'), (2, 'adult'), (0, 'teen'), (1, 'youngester')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Blood_Pressure',
            field=models.PositiveIntegerField(choices=[(0, 'Low'), (2, 'High'), (1, 'Normal')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Cholesterol_Level',
            field=models.PositiveIntegerField(choices=[(0, 'Low'), (2, 'High'), (1, 'Normal')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Disease',
            field=models.PositiveIntegerField(choices=[(2, 'Hepatitis B'), (10, 'Hypertension'), (2, 'Malaria'), (2, 'Rabies'), (2, 'Hemophilia'), (2, 'HIV/AIDS'), (14, 'Osteoporosis'), (7, 'Hyperthyroidism'), (2, 'Ebola Virus'), (2, 'Mumps'), (2, 'Tetanus'), (16, 'Stroke'), (8, 'Bronchitis'), (6, 'Common Cold'), (10, 'Migraine'), (6, 'Rheumatoid Arthritis'), (2, 'Typhoid Fever'), (5, 'Pancreatitis'), (5, 'Urinary Tract Infection'), (2, 'Rubella'), (5, 'Multiple Sclerosis'), (6, 'Allergic Rhinitis'), (6, 'Depression'), (8, 'Pneumonia'), (5, 'Coronary Artery Disease'), (2, 'Cholera'), (6, 'Anxiety Disorders'), (2, 'Lyme Disease'), (5, 'Ulcerative Colitis'), (6, 'Kidney Cancer'), (23, 'Asthma'), (5, 'Liver Disease'), (5, 's Disease"'), (6, 'Liver Cancer'), (2, 'Zika Virus'), (6, 'Eczema'), (7, 'Hypothyroidism'), (3, 'Hepatitis'), (2, 'Measles'), (5, 'Psoriasis'), (4, 'Chronic Obstructive Pulmonary Disease (COPD)'), (2, 'Chickenpox'), (10, 'Diabetes'), (2, 'Dengue Fever'), (1, 'Others'), (8, 'Influenza'), (3, 'Urinary Tract Infection (UTI)'), (2, 'Klinefelter Syndrome'), (6, 'Osteoarthritis'), (2, 'Turner Syndrome'), (6, 'Gastroenteritis'), (3, 'Lung Cancer'), (3, 'Tuberculosis'), (5, 'Kidney Disease')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Gender',
            field=models.PositiveIntegerField(choices=[(1, 'Male'), (0, 'Female')]),
        ),
    ]
