# Generated by Django 5.0.1 on 2024-01-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0010_alter_data_age_alter_data_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.PositiveIntegerField(choices=[(1, 'youngester'), (3, 'senior citizen'), (2, 'adult'), (0, 'teen')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Blood_Pressure',
            field=models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Low'), (2, 'High')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Cholesterol_Level',
            field=models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Low'), (2, 'High')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Cough',
            field=models.PositiveIntegerField(choices=[(0, 'Yes'), (1, 'No')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Difficult_Breathing',
            field=models.PositiveIntegerField(choices=[(0, 'Yes'), (1, 'No')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Disease',
            field=models.PositiveIntegerField(choices=[(2, 'Zika Virus'), (5, 'Multiple Sclerosis'), (2, 'Chickenpox'), (5, 'Urinary Tract Infection'), (2, 'Malaria'), (6, 'Osteoarthritis'), (5, 'Kidney Disease'), (2, 'Hepatitis B'), (2, 'Hemophilia'), (2, 'Typhoid Fever'), (2, 'Rubella'), (5, 'Psoriasis'), (4, 'Chronic Obstructive Pulmonary Disease (COPD)'), (6, 'Liver Cancer'), (6, 'Depression'), (7, 'Hypothyroidism'), (3, 'Urinary Tract Infection (UTI)'), (5, 'Ulcerative Colitis'), (6, 'Eczema'), (5, 'Liver Disease'), (6, 'Anxiety Disorders'), (1, 'Others'), (6, 'Common Cold'), (8, 'Bronchitis'), (2, 'Measles'), (2, 'HIV/AIDS'), (2, 'Ebola Virus'), (5, 's Disease"'), (2, 'Turner Syndrome'), (3, 'Hepatitis'), (10, 'Diabetes'), (14, 'Osteoporosis'), (6, 'Gastroenteritis'), (2, 'Mumps'), (23, 'Asthma'), (5, 'Pancreatitis'), (2, 'Lyme Disease'), (3, 'Lung Cancer'), (16, 'Stroke'), (5, 'Coronary Artery Disease'), (6, 'Allergic Rhinitis'), (10, 'Migraine'), (6, 'Rheumatoid Arthritis'), (7, 'Hyperthyroidism'), (3, 'Tuberculosis'), (8, 'Influenza'), (2, 'Rabies'), (8, 'Pneumonia'), (2, 'Klinefelter Syndrome'), (2, 'Cholera'), (2, 'Tetanus'), (6, 'Kidney Cancer'), (10, 'Hypertension'), (2, 'Dengue Fever')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Fatigue',
            field=models.PositiveIntegerField(choices=[(0, 'Yes'), (1, 'No')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='Fever',
            field=models.PositiveIntegerField(choices=[(0, 'Yes'), (1, 'No')]),
        ),
    ]
