# Generated by Django 5.0.1 on 2024-01-26 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0011_alter_data_age_alter_data_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.PositiveIntegerField(choices=[(0, 'teen'), (1, 'youngester'), (2, 'adult'), (3, 'senior citizen')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Blood_Pressure',
            field=models.PositiveIntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Cholesterol_Level',
            field=models.PositiveIntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Cough',
            field=models.PositiveIntegerField(choices=[(0, 'Yes'), (1, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Difficult_Breathing',
            field=models.PositiveIntegerField(choices=[(0, 'Yes'), (1, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Disease',
            field=models.PositiveIntegerField(choices=[(23, 'Asthma'), (16, 'Stroke'), (14, 'Osteoporosis'), (10, 'Hypertension'), (10, 'Diabetes'), (10, 'Migraine'), (8, 'Influenza'), (8, 'Pneumonia'), (8, 'Bronchitis'), (7, 'Hyperthyroidism'), (7, 'Hypothyroidism'), (6, 'Rheumatoid Arthritis'), (6, 'Gastroenteritis'), (6, 'Anxiety Disorders'), (6, 'Allergic Rhinitis'), (6, 'Eczema'), (6, 'Common Cold'), (6, 'Depression'), (6, 'Liver Cancer'), (6, 'Kidney Cancer'), (6, 'Osteoarthritis'), (5, 'Coronary Artery Disease'), (5, 'Kidney Disease'), (5, 'Ulcerative Colitis'), (5, 'Pancreatitis'), (5, 'Psoriasis'), (5, 'Multiple Sclerosis'), (5, 'Urinary Tract Infection'), (5, 'Liver Disease'), (5, 's Disease"'), (4, 'Chronic Obstructive Pulmonary Disease (COPD)'), (3, 'Hepatitis'), (3, 'Tuberculosis'), (3, 'Lung Cancer'), (3, 'Urinary Tract Infection (UTI)'), (2, 'Cholera'), (2, 'Rubella'), (2, 'Ebola Virus'), (2, 'Malaria'), (2, 'Dengue Fever'), (2, 'Mumps'), (2, 'Klinefelter Syndrome'), (2, 'Lyme Disease'), (2, 'Rabies'), (2, 'Turner Syndrome'), (2, 'Tetanus'), (2, 'Zika Virus'), (2, 'HIV/AIDS'), (2, 'Hemophilia'), (2, 'Measles'), (2, 'Chickenpox'), (2, 'Typhoid Fever'), (2, 'Hepatitis B'), (1, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Fatigue',
            field=models.PositiveIntegerField(choices=[(0, 'Yes'), (1, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Fever',
            field=models.PositiveIntegerField(choices=[(0, 'Yes'), (1, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Gender',
            field=models.PositiveIntegerField(choices=[(0, 'Female'), (1, 'Male')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='data',
            name='classification',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
