# Generated by Django 5.0.1 on 2024-01-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0016_alter_data_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Disease',
            field=models.PositiveIntegerField(choices=[(23, 'Asthma'), (16, 'Stroke'), (1, 'Others')], null=True),
        ),
    ]
